# Config for https://github.com/probot/semantic-pull-requests

# Always validate the PR title, and ignore the commits
titleOnly: true
types:
  # To do a major relase, put "BREAKING CHANGE: ..." in the message
  # Minor Release
  - feat
  # Patch Release
  - fix
  - perf
  # No Release
  - docs
  - chore
